### ISSUE TITLE
DEV: temp_room.ejs에 chatList 질문!

### ISSUE THREAD

**Issue by gomamon** [serverdevcamp/camp4_1park2lee#37]
도움이 필요합니다!
바보같은 질문이지만,

아무리봐도 서버에 보다 프론트에 문제가 있는거 같아 질문합니다!
develop 브랜치의 ejs코드를 다시 살펴보다가,

(develop브랜치)언니 코드에서 질문이 있습니다.

`chat/veiws/tempRoom.ejs`
```
  <div class="container">
    <h3 id="room"><%= roomName %></h3>
    <div class="container" style="height: 700px;">
      <ul id="chat">
        <% for(i = 0; i < chatList.length; i++){ %>
          <% if(chatList[i].chatUserId == userId){ %>
            <li style="margin-left: 80%; list-style: none"><%= chatList[i].chatMsg%></li>
          <% }else{ %>  
            <li style="margin-left: 8%; list-style: none"><%= chatList[i].chatUserName%>: <%= chatList[i].chatMsg%></li>
          <% } }%>   
      </ul>
    </div>
```

여기서 chatList를 만들어주는 부분이 어디에있는지 못찾겠습니다.

api통신 부분을 확인해봐도
```
router.get('/:userId/:roomId', async function (req, res, next) {
  //나중에 여기 auth 미들웨어 이용, token 값으로 사용자 정보 가져와서 방 입장
  const userID = await req.params.userId;
  const roomID = await req.params.roomId;

  var roomInfo = await handleDb.readRoom(userID, roomID);

  try {
    res.status(200).render('tempRoom.ejs', roomInfo);
    return;
  } catch (err) {
    res.status(200).json({
      message: "enter room - server error."
    })
    return;
  }
});
```
userID랑 roomID 밖에 없어서
`socket.js` 부분을 봐도 해당 변수를 찾을 수가 없어서요! 

서투른 부분이 많아 너무 오래걸리네요 ㅠㅠ 꼭 해결하고 월욜날 가겠습니다!ㅠㅠ 

도와주세요!!

**Comment by Ju-Yeon** [comment]
먼저  프론트의 chatList를 만들어주는 부분입니당
`route/room.js'에 보면
`
//방 입장
router.get('/:userId/:roomId', async function (req, res, next) {
  //나중에 여기 auth 미들웨어 이용, token 값으로 사용자 정보 가져와서 방 입장
  const userID = await req.params.userId;
  const roomID = await req.params.roomId;

  var roomInfo = await handleDb.readRoom(userID, roomID);

  try {
    res.status(200).render('tempRoom.ejs', roomInfo);
    return;

  } catch (err) {
    res.status(200).json({
      message: "enter room - server error."
    })
    return;
  }
});
`
여기에서 roomInfo를 handleDb의 readRoom모듈에서 가져오는데요.
`module/handleDb.js'에서 해당 함수를 보면
`
module.exports = {
    /*
    이때 방 정보에서 chat이 있는 방 정보만 가져오는 거로 수정할 것! roomInfo
   */
    readRoom: async (userId, roomId) => {

        var chatList = []
        room_in_db = await rooms.findById(roomId)

        //room_in_db.chat.forEach( async (chatId) => {
        for (var chatId of room_in_db.chat) {
            await chats.findById(chatId)
                .then((chat_in_db) => {
                    var chat_info = {
                        "chatUserName": chat_in_db.speaker,
                        "chatUserId": chat_in_db.speaker,
                        "chatMsg": chat_in_db.originContext,
                    }
                    return chat_info;
                })
                .then((resultChat) => {
                    chatList.push(resultChat)
                });
        }

        var result = {
            "userName": userId,
            "userId": userId,
            "roomName": room_in_db.name,
            "roomId": room_in_db._id,
            "chatList": chatList
        }
        //console.log(result)

        return result;

    },
`로 되어있습니다. 
말그대로 기존 방의 채팅내용을 가져와서 chatList에 담아 저 내용을 그대로 tempRoom.ejs에 띄어주는 거죠!

제가 생각을 했을 때 저 roomInfo의 내용의 기존의 방정보를 띄어주는 부분인데, 
금요일까지의 예은이 이슈는 기존의 대화내용이 불러지는게 아니라 실시간으로 소켓을 받았을 때 대화내용을 보여주는 

`/views/tempRoom.ejs`의
`
  // 서버로부터의 메시지를 받을 때
      this.socket.on('server chat message', function (data) {
        if (data.user == <%= userId %>) {
        $("#chat").append($('<li style="margin-left: 80%; list-style: none">').text(`${data.msg}`));
      } else {
        $("#chat").append($('<li style="margin-left: 8%; list-style: none";">').text(`${data.user}: ${data.msg}`));
      }
    });
`
이 append부분이라고 생각합니다. 
아니면 기존의 대화가 안불러지는게 문제가 되었나요?  
어느부분이 지금의 이슈인지는 모르겠네요!

**Comment by Ju-Yeon** [comment]
추가로 제가 참고한 다큐먼트는 아래와 같습니다..
조금씩 다 달라서 하나만 본건 아니지만 주로 읽었던 문서입니당

pubsub구조를 이용한 socket.io예시
`https://stackoverflow.com/questions/32743754/using-redis-as-pubsub-over-socket-io`

3기 분의 블로그
`https://1ilsang.blog.me/221231504174`
3기 분의 백엔드 github
`https://github.com/1ilsang/BEWE/blob/master/BACKEND/ChatApiServer/socket/socketService.js`
3기 분의 프론트엔드 github (이 부분이 100% 맞는 부분인지는 모르겠어용)
`https://github.com/1ilsang/BEWE/blob/master/FRONTEND/ReactReduxVer_1/src/components/chatt/ChatApp.js
`

**Comment by gomamon** [comment]
대화내용이 안불러지는 issue도 있어서 해당 부분 해결 할 수 있을것 같습니다!!
감사합니다!

**Comment by gomamon** [comment]
성공!
