### ISSUE TITLE
DEV:receive requests by rabbitMQ

### ISSUE THREAD

**Issue by Below0** [serverdevcamp/camp4_1park2lee#46]

**Comment by Ju-Yeon** [comment]
spell server 요청 부분입니당
먼저 `src/chat/module/handleDb.js`에서 **spell.checkSpell()**요청을 하고
```
    saveChat: (content) => {

        var chatModel = new chats();
        chatModel.speaker = content.user;
        chatModel.origin_context = content.msg;
        chatModel.room = content.room;
        chatModel.save()
            .then(async function (newChat) {
                **spell.checkSpell(newChat.speaker, newChat._id); //spell 서버 요청**

                console.log(`대화 "${newChat.origin_context}" 저장 완료`)

                room_chats.create({
                    room_id: newChat.room,
                    chat_id: String(newChat._id)
                }).then((new_room_chats) => {
                    console.log("room_chats 저장 완료")
                }).catch((err) => {
                    console.log(err,"room_chats 저장 실패")
                })
            })
            .catch((err) => {
                console.log("대화 저장 실패:", err)
            })
    }
```
 saveChat함수에서 요청이 들어오면 `src/chat/module/spellCheck.js`에서
```
module.exports = {
    checkSpell : async( userID, chatID ) => {

        let chat = await chats.findById(chatID);
        request.post({
            url: 'http://127.0.0.1:3001/spell',
            form: {
                context: chat.origin_context,
                reqId: userID,
                userId: chatID
            }
        }, (err, response, body) => {

            if (!response.err && response.statusCode == 200) {

                //console.log(body);
                result = JSON.parse(body)

                if (result.errors != 0) {
                    chat.check_context =result.correct;
                    chat.status = 0;
                } else {
                    chat.status = 1;
                }
                chat.save()
                    .then(( afterCheck ) => {
                        console.log("spell check 완료");
                    })
                    .catch((err) => {
                        console.log("spell check 실패 :", err);
                    })
                }
        });
    }
}
```
응답을 받다 result값으로 데이터베이스를 갱신해주고 save 해줍니다.

**Comment by Below0** [comment]
`let sync_request = require('sync-request');
let amqp = require('amqplib')
let chats = require('../model/chat');
let request = require('request');


module.exports = {
    checkSpell: async (userID, chatID) => {

        let chat = await chats.findById(chatID);
        let queue = 'spellQueue';

        let msg = {
            context: chat.origin_context,
            reqId: userID,
            userId: chatID
        };

        amqp.connect('amqp://localhost', function (error0, connection) {
            if (error0) {
                throw error0;
            }
            connection.createChannel(function (error1, channel) {
                if (error1) {
                    throw error1;
                }

                channel.assertQueue(queue, {
                    durable: false
                });

                channel.sendToQueue(queue, Buffer.from(JSON.stringify(msg)), {
                    replyTo: 'chatQueue'
                });
                console.log(" [x] Sent %s", msg);
                setTimeout(function () {
                    connection.close();
                }, 500);
            });
        });
    },
    recvFormQueue: () => {
        amqp.connect('amqp://localhost', function (error0, connection) {
            if (error0) {
                throw error0;
            }
            connection.createChannel(function (error1, channel) {
                if (error1) {
                    throw error1;
                }

                channel.assertQueue(queue, {
                    durable: false
                });

                channel.consume(queue, function (msg) {
                    let result = JSON.parse(JSON.parse(msg.content));
                    console.log(" [x] Received %s", result);
                    
                    if (result.errors != 0) {
                        chat.check_context = result.correct;
                        chat.status = 0;
                    } else {
                        chat.status = 1;
                    }
                    
                    chat.save()
                        .then((afterCheck) => {
                            console.log("spell check 완료");
                        })
                        .catch((err) => {
                            console.log("spell check 실패 :", err);
                        })

                }, {
                    noAck: true
                });
            });
        });
    }
}`
일단 몽고db 안되서 직접 돌려보지는 못했는데 이렇게 바꿨습니다!! 내일 직접 테스트해봐야할거같습니더
`npm install --save amqplib`

**Comment by Below0** [comment]
아 그리고 app.js  에서 recvFromQueue() 처음에 한번 실행해줘야합니다!!

**Comment by Below0** [comment]
#52
